#!/bin/bash
if [ -z $1 ]; then
        echo "Usage: 'ct_installer COMMAND'"
        echo "To install run 'ct_instaler install'"
        echo "To install to a custom location, run 'ct_installer install_to LOCATION'"
        echo "To update the installer call 'ct_installer update_installer'"
        return
fi
case $1 in
        'install')
                mkdir ~/.commandstool &> /dev/null
                source ct_installer install_to ~/.commandstool/ct
                commandstool test_install
                ;;
        'install_to')
                read -n1 -p "Are you sure you want to do this? [y/n]:" call_safetey && echo
                if [ "$call_safetey" = "y" ]; then
                        wget -O $1 https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/commandstool                                chmod +x $1
                        mkdir ~/.commandstool &> /dev/null
                        echo $1 > ~/.commandstool/config/script_location
                        source $1 init_ct
                        echo "source $1 init_ct" >> ~/.bashrc
                        update_bash
                        commandstool reset &> /dev/null # If commandstool was installed before, reset it.
                        commandstool test_install
                else
                        echo Abort Installation
                fi
                ;;
        'update_installer')
                rm ct_installer
                wget https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/ct_installer
                chmod +rwx ct_installer
                source ct_installer
                ;;
        *)
                echo "Invalid command"
                ;;
esac
