#!/bin/bash
install() {
        read -n1 -p "Are you sure you want to do this? [y/n]:" call_safetey && echo
        if [ "$call_safetey" = "y" ]; then
                wget -O ~/.bash_aliases https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/commandstool
                source ~/.bashrc
                echo "Testing installation"
                commands_tool_test
        else
                echo Abort Installation
        fi
}

install_custom_location() {
        read -n1 -p "Are you sure you want to do this? [y/n]:" call_safetey && echo
        if [ "$call_safetey" = "y" ]; then
                wget -O $1 https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/commandstool
                chmod +x $1
                source $1
                commands_tool_set_file_location $1
                echo "source $1" >> ~/.bashrc
                update_bash
                commands_tool_reset
                echo "Testing installation"
                commands_tool_test
        else
                echo Abort Installation
        fi
}

update_installer() {
        rm ct_installer
        wget https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/ct_installer
        chmod +rwx ct_installer
        source ct_installer
}
