#!/bin/bash
echo "Starting test"
echo "Accept prompts where necessary"
echo
echo "Out of repo function test"
ct try https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/test_external -p
ct install https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/test_external -p
ct uninstall test_external
echo "Out of repo test complete. Moving on to in-repo function test"
ct try test_internal
ct install test_internal
ct uninstall test_internal
echo "In-repo function test complete."
echo "Testing complete. Feel free to run uninstall_tests now."
echo "Or you can run more_test_ct to run other tests. These could be destructive so they will prompt you if you are sure you want to do each one."
echo "Exit"
