#!/bin/bash

testing() {
    echo "Test suite for Commands Tool was installed"
    echo "Type in test_ct to start the test"
}

test_ct() {
    echo "Starting test"
    echo "Accept prompts where necessary"
    echo
    echo "Out of repo function test"
    try_plugin https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/test_external
    install_plugin https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/test_external
    uninstall_plugin https://raw.githubusercontent.com/AdrianVovk/BashCommands/master/test_external
    echo "Out of repo test complete. Moving on to in-repo function test"
    try_plugin test_internal
    install_plugin test_internal
    uninstall_plugin test_internal
    echo "In-repo function test complete."
    echo "Testing complete. Feel free to run uninstall_tests now."
    echo "Or you can run more_test_ct to run other tests. These could be destructive so they will prompt you if you are sure you want to do each one.
    echo "Exit"
}
