#!/bin/bash
windows_commands() {
        echo "Windows Commands plugin"
        echo "By Adrian Vovk"
        echo
        windows_commands_help
        echo
        echo "To see this help message again, run 'windows_commands_help'"
}

windows_commands_help() {
        echo "Windows Commands: Installed commands"
        echo "All of these commands do what they would on windows."
        echo "dir"
        echo "cls"
        echo "print"
        echo "del"
        echo "pause"
        echo "echo."
}

alias dir='la'
alias cls='clear'
alias print='cat'
alias del='rm'
pause() {
        # Using this for if statements
        if [ -z "$1" ]; then
                read -n1 -s -p "Press any key to continue..." key
        else
                read -n1 -s -p $1 key
        fi
        echo
}
alias echo.='echo'
